#include <stdio.h> 

int main()
{
    printf  
    ("Holla pedazo de verga"); 
    printf("/MI NOMBRE ES MAXIMO DECIMO MERIDO, GENERAL DE LOS EJERCITOS DEL NOMBRE, PADRE DE UN HIJO ASESINADO, ESPOSO DE UNA MUJER ASESINADA. SERVIDOR DEL AUTENTICO EMPERADOR: MARCO AURELIO");

    return 0;
}